CREATE TABLE IF NOT EXISTS products (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    shop_id BIGINT UNSIGNED NOT NULL,
    category_id BIGINT UNSIGNED NOT NULL,
    sku VARCHAR(100) NOT NULL,
    name VARCHAR(180) NOT NULL,
    slug VARCHAR(180) NOT NULL,
    brand VARCHAR(120) NULL,
    description TEXT NULL,
    product_type ENUM('garment', 'equipment', 'accessory', 'other') NOT NULL DEFAULT 'other',
    daily_rental_rate DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    weekly_rental_rate DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    monthly_rental_rate DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    security_deposit DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    status ENUM('active', 'inactive', 'draft') NOT NULL DEFAULT 'draft',
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_products_shop FOREIGN KEY (shop_id) REFERENCES shops(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    UNIQUE KEY uq_products_shop_sku (shop_id, sku),
    UNIQUE KEY uq_products_shop_slug (shop_id, slug),
    KEY idx_products_shop_category (shop_id, category_id),
    KEY idx_products_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
