CREATE TABLE IF NOT EXISTS inventory_items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    shop_id BIGINT UNSIGNED NOT NULL,
    product_id BIGINT UNSIGNED NOT NULL,
    item_code VARCHAR(80) NOT NULL,
    size VARCHAR(50) NULL,
    color VARCHAR(50) NULL,
    condition_status ENUM('available', 'rented', 'maintenance', 'damaged', 'retired') NOT NULL DEFAULT 'available',
    purchase_price DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    current_value DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    acquired_at TIMESTAMP NULL DEFAULT NULL,
    last_service_at TIMESTAMP NULL DEFAULT NULL,
    notes TEXT NULL,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_inventory_items_shop FOREIGN KEY (shop_id) REFERENCES shops(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_inventory_items_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    UNIQUE KEY uq_inventory_items_shop_code (shop_id, item_code),
    KEY idx_inventory_items_shop_product (shop_id, product_id),
    KEY idx_inventory_items_status (condition_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
