-- PostgreSQL migration: Create location lookup tables

CREATE TABLE IF NOT EXISTS location_states (
    id SMALLSERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_location_states_name ON location_states (name);

CREATE TABLE IF NOT EXISTS location_cities (
    id SERIAL PRIMARY KEY,
    state_id SMALLINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    CONSTRAINT fk_location_cities_state
        FOREIGN KEY (state_id) REFERENCES location_states(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_location_cities_state_name ON location_cities (state_id, name);
CREATE INDEX IF NOT EXISTS idx_location_cities_name ON location_cities (name);

-- Seed: Indian states and union territories
INSERT INTO location_states (name) VALUES
    ('Andhra Pradesh'),
    ('Arunachal Pradesh'),
    ('Assam'),
    ('Bihar'),
    ('Chhattisgarh'),
    ('Goa'),
    ('Gujarat'),
    ('Haryana'),
    ('Himachal Pradesh'),
    ('Jharkhand'),
    ('Karnataka'),
    ('Kerala'),
    ('Madhya Pradesh'),
    ('Maharashtra'),
    ('Manipur'),
    ('Meghalaya'),
    ('Mizoram'),
    ('Nagaland'),
    ('Odisha'),
    ('Punjab'),
    ('Rajasthan'),
    ('Sikkim'),
    ('Tamil Nadu'),
    ('Telangana'),
    ('Tripura'),
    ('Uttar Pradesh'),
    ('Uttarakhand'),
    ('West Bengal'),
    ('Andaman and Nicobar Islands'),
    ('Chandigarh'),
    ('Dadra and Nagar Haveli and Daman and Diu'),
    ('Delhi'),
    ('Jammu and Kashmir'),
    ('Ladakh'),
    ('Lakshadweep'),
    ('Puducherry')
ON CONFLICT (name) DO NOTHING;

-- Seed: Cities
INSERT INTO location_cities (state_id, name)
SELECT s.id, city_data.city_name
FROM location_states s
JOIN (VALUES
    ('Andhra Pradesh', 'Amaravati'),
    ('Andhra Pradesh', 'Guntur'),
    ('Andhra Pradesh', 'Tirupati'),
    ('Andhra Pradesh', 'Vijayawada'),
    ('Andhra Pradesh', 'Visakhapatnam'),
    ('Arunachal Pradesh', 'Itanagar'),
    ('Arunachal Pradesh', 'Naharlagun'),
    ('Arunachal Pradesh', 'Pasighat'),
    ('Assam', 'Dibrugarh'),
    ('Assam', 'Guwahati'),
    ('Assam', 'Jorhat'),
    ('Assam', 'Silchar'),
    ('Bihar', 'Bhagalpur'),
    ('Bihar', 'Gaya'),
    ('Bihar', 'Muzaffarpur'),
    ('Bihar', 'Patna'),
    ('Chhattisgarh', 'Bhilai'),
    ('Chhattisgarh', 'Bilaspur'),
    ('Chhattisgarh', 'Raipur'),
    ('Goa', 'Mapusa'),
    ('Goa', 'Margao'),
    ('Goa', 'Panaji'),
    ('Gujarat', 'Ahmedabad'),
    ('Gujarat', 'Gandhinagar'),
    ('Gujarat', 'Rajkot'),
    ('Gujarat', 'Surat'),
    ('Haryana', 'Faridabad'),
    ('Haryana', 'Gurugram'),
    ('Haryana', 'Hisar'),
    ('Haryana', 'Panipat'),
    ('Himachal Pradesh', 'Dharamshala'),
    ('Himachal Pradesh', 'Mandi'),
    ('Himachal Pradesh', 'Shimla'),
    ('Himachal Pradesh', 'Solan'),
    ('Jharkhand', 'Bokaro'),
    ('Jharkhand', 'Dhanbad'),
    ('Jharkhand', 'Jamshedpur'),
    ('Jharkhand', 'Ranchi'),
    ('Karnataka', 'Bengaluru'),
    ('Karnataka', 'Hubballi'),
    ('Karnataka', 'Mangaluru'),
    ('Karnataka', 'Mysuru'),
    ('Kerala', 'Kochi'),
    ('Kerala', 'Kozhikode'),
    ('Kerala', 'Thiruvananthapuram'),
    ('Kerala', 'Thrissur'),
    ('Madhya Pradesh', 'Bhopal'),
    ('Madhya Pradesh', 'Gwalior'),
    ('Madhya Pradesh', 'Indore'),
    ('Madhya Pradesh', 'Jabalpur'),
    ('Maharashtra', 'Chhatrapati Sambhajinagar'),
    ('Maharashtra', 'Mumbai'),
    ('Maharashtra', 'Nagpur'),
    ('Maharashtra', 'Nashik'),
    ('Maharashtra', 'Pune'),
    ('Manipur', 'Imphal'),
    ('Meghalaya', 'Shillong'),
    ('Mizoram', 'Aizawl'),
    ('Nagaland', 'Dimapur'),
    ('Nagaland', 'Kohima'),
    ('Odisha', 'Bhubaneswar'),
    ('Odisha', 'Cuttack'),
    ('Odisha', 'Rourkela'),
    ('Punjab', 'Amritsar'),
    ('Punjab', 'Jalandhar'),
    ('Punjab', 'Ludhiana'),
    ('Punjab', 'Mohali'),
    ('Rajasthan', 'Ajmer'),
    ('Rajasthan', 'Jaipur'),
    ('Rajasthan', 'Jodhpur'),
    ('Rajasthan', 'Udaipur'),
    ('Sikkim', 'Gangtok'),
    ('Tamil Nadu', 'Chennai'),
    ('Tamil Nadu', 'Coimbatore'),
    ('Tamil Nadu', 'Madurai'),
    ('Tamil Nadu', 'Tiruchirappalli'),
    ('Tamil Nadu', 'Tirunelveli'),
    ('Telangana', 'Hyderabad'),
    ('Telangana', 'Karimnagar'),
    ('Telangana', 'Warangal'),
    ('Tripura', 'Agartala'),
    ('Uttar Pradesh', 'Agra'),
    ('Uttar Pradesh', 'Ghaziabad'),
    ('Uttar Pradesh', 'Kanpur'),
    ('Uttar Pradesh', 'Lucknow'),
    ('Uttar Pradesh', 'Varanasi'),
    ('Uttarakhand', 'Dehradun'),
    ('Uttarakhand', 'Haridwar'),
    ('Uttarakhand', 'Nainital'),
    ('West Bengal', 'Asansol'),
    ('West Bengal', 'Durgapur'),
    ('West Bengal', 'Howrah'),
    ('West Bengal', 'Kolkata'),
    ('Andaman and Nicobar Islands', 'Port Blair'),
    ('Chandigarh', 'Chandigarh'),
    ('Dadra and Nagar Haveli and Daman and Diu', 'Daman'),
    ('Dadra and Nagar Haveli and Daman and Diu', 'Silvassa'),
    ('Delhi', 'Delhi'),
    ('Jammu and Kashmir', 'Jammu'),
    ('Jammu and Kashmir', 'Srinagar'),
    ('Ladakh', 'Leh'),
    ('Ladakh', 'Kargil'),
    ('Lakshadweep', 'Kavaratti'),
    ('Puducherry', 'Karaikal'),
    ('Puducherry', 'Puducherry')
) AS city_data(state_name, city_name) ON city_data.state_name = s.name
ON CONFLICT (state_id, name) DO NOTHING;
